// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/route.proto

package grpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamResponse_StreamType int32

const (
	StreamResponse_Chat   StreamResponse_StreamType = 0
	StreamResponse_Joined StreamResponse_StreamType = 1
	StreamResponse_Leaved StreamResponse_StreamType = 2
)

var StreamResponse_StreamType_name = map[int32]string{
	0: "Chat",
	1: "Joined",
	2: "Leaved",
}

var StreamResponse_StreamType_value = map[string]int32{
	"Chat":   0,
	"Joined": 1,
	"Leaved": 2,
}

func (x StreamResponse_StreamType) String() string {
	return proto.EnumName(StreamResponse_StreamType_name, int32(x))
}

func (StreamResponse_StreamType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{14, 0}
}

type Room struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Player struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Chat struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{2}
}

func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *Chat) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Chat) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GetTokenRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{3}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTokenResult struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResult) Reset()         { *m = GetTokenResult{} }
func (m *GetTokenResult) String() string { return proto.CompactTextString(m) }
func (*GetTokenResult) ProtoMessage()    {}
func (*GetTokenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{4}
}

func (m *GetTokenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResult.Unmarshal(m, b)
}
func (m *GetTokenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResult.Marshal(b, m, deterministic)
}
func (m *GetTokenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResult.Merge(m, src)
}
func (m *GetTokenResult) XXX_Size() int {
	return xxx_messageInfo_GetTokenResult.Size(m)
}
func (m *GetTokenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResult proto.InternalMessageInfo

func (m *GetTokenResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetTokenResult) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type RefreshTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{5}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

type RefreshTokenResult struct {
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResult) Reset()         { *m = RefreshTokenResult{} }
func (m *RefreshTokenResult) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResult) ProtoMessage()    {}
func (*RefreshTokenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{6}
}

func (m *RefreshTokenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResult.Unmarshal(m, b)
}
func (m *RefreshTokenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResult.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResult.Merge(m, src)
}
func (m *RefreshTokenResult) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResult.Size(m)
}
func (m *RefreshTokenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResult.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResult proto.InternalMessageInfo

func (m *RefreshTokenResult) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type JoinRoomRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{7}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *JoinRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinRoomResult struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Room                 *Room     `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Players              []*Player `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Chats                []*Chat   `protobuf:"bytes,4,rep,name=chats,proto3" json:"chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoomResult) Reset()         { *m = JoinRoomResult{} }
func (m *JoinRoomResult) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResult) ProtoMessage()    {}
func (*JoinRoomResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{8}
}

func (m *JoinRoomResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResult.Unmarshal(m, b)
}
func (m *JoinRoomResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResult.Marshal(b, m, deterministic)
}
func (m *JoinRoomResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResult.Merge(m, src)
}
func (m *JoinRoomResult) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResult.Size(m)
}
func (m *JoinRoomResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResult.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResult proto.InternalMessageInfo

func (m *JoinRoomResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *JoinRoomResult) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *JoinRoomResult) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *JoinRoomResult) GetChats() []*Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

type LeaveRoomRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomRequest) Reset()         { *m = LeaveRoomRequest{} }
func (m *LeaveRoomRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomRequest) ProtoMessage()    {}
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{9}
}

func (m *LeaveRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomRequest.Unmarshal(m, b)
}
func (m *LeaveRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomRequest.Marshal(b, m, deterministic)
}
func (m *LeaveRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomRequest.Merge(m, src)
}
func (m *LeaveRoomRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomRequest.Size(m)
}
func (m *LeaveRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomRequest proto.InternalMessageInfo

func (m *LeaveRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type LeaveRoomResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomResult) Reset()         { *m = LeaveRoomResult{} }
func (m *LeaveRoomResult) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomResult) ProtoMessage()    {}
func (*LeaveRoomResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{10}
}

func (m *LeaveRoomResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomResult.Unmarshal(m, b)
}
func (m *LeaveRoomResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomResult.Marshal(b, m, deterministic)
}
func (m *LeaveRoomResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomResult.Merge(m, src)
}
func (m *LeaveRoomResult) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomResult.Size(m)
}
func (m *LeaveRoomResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomResult.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomResult proto.InternalMessageInfo

func (m *LeaveRoomResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type MessageRoomRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRoomRequest) Reset()         { *m = MessageRoomRequest{} }
func (m *MessageRoomRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRoomRequest) ProtoMessage()    {}
func (*MessageRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{11}
}

func (m *MessageRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRoomRequest.Unmarshal(m, b)
}
func (m *MessageRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRoomRequest.Marshal(b, m, deterministic)
}
func (m *MessageRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRoomRequest.Merge(m, src)
}
func (m *MessageRoomRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRoomRequest.Size(m)
}
func (m *MessageRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRoomRequest proto.InternalMessageInfo

func (m *MessageRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *MessageRoomRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MessageRoomResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRoomResult) Reset()         { *m = MessageRoomResult{} }
func (m *MessageRoomResult) String() string { return proto.CompactTextString(m) }
func (*MessageRoomResult) ProtoMessage()    {}
func (*MessageRoomResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{12}
}

func (m *MessageRoomResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRoomResult.Unmarshal(m, b)
}
func (m *MessageRoomResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRoomResult.Marshal(b, m, deterministic)
}
func (m *MessageRoomResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRoomResult.Merge(m, src)
}
func (m *MessageRoomResult) XXX_Size() int {
	return xxx_messageInfo_MessageRoomResult.Size(m)
}
func (m *MessageRoomResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRoomResult.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRoomResult proto.InternalMessageInfo

func (m *MessageRoomResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type StreamRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{13}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type StreamResponse struct {
	Type                 StreamResponse_StreamType `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.StreamResponse_StreamType" json:"type,omitempty"`
	Chat                 *Chat                     `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
	Player               *Player                   `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d63760fefd55df2f, []int{14}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetType() StreamResponse_StreamType {
	if m != nil {
		return m.Type
	}
	return StreamResponse_Chat
}

func (m *StreamResponse) GetChat() *Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

func (m *StreamResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterEnum("grpc.StreamResponse_StreamType", StreamResponse_StreamType_name, StreamResponse_StreamType_value)
	proto.RegisterType((*Room)(nil), "grpc.Room")
	proto.RegisterType((*Player)(nil), "grpc.Player")
	proto.RegisterType((*Chat)(nil), "grpc.Chat")
	proto.RegisterType((*GetTokenRequest)(nil), "grpc.GetTokenRequest")
	proto.RegisterType((*GetTokenResult)(nil), "grpc.GetTokenResult")
	proto.RegisterType((*RefreshTokenRequest)(nil), "grpc.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResult)(nil), "grpc.RefreshTokenResult")
	proto.RegisterType((*JoinRoomRequest)(nil), "grpc.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResult)(nil), "grpc.JoinRoomResult")
	proto.RegisterType((*LeaveRoomRequest)(nil), "grpc.LeaveRoomRequest")
	proto.RegisterType((*LeaveRoomResult)(nil), "grpc.LeaveRoomResult")
	proto.RegisterType((*MessageRoomRequest)(nil), "grpc.MessageRoomRequest")
	proto.RegisterType((*MessageRoomResult)(nil), "grpc.MessageRoomResult")
	proto.RegisterType((*StreamRequest)(nil), "grpc.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "grpc.StreamResponse")
}

func init() { proto.RegisterFile("grpc/route.proto", fileDescriptor_d63760fefd55df2f) }

var fileDescriptor_d63760fefd55df2f = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x8d, 0x13, 0xd7, 0x4d, 0xc7, 0xfd, 0x92, 0x7c, 0xd3, 0xa6, 0x35, 0xb9, 0xa0, 0x61, 0x05,
	0x28, 0x50, 0x14, 0x50, 0x7a, 0x51, 0x55, 0x42, 0x48, 0x80, 0x10, 0x2a, 0xe2, 0x4f, 0x6e, 0xef,
	0x23, 0x93, 0x0c, 0x4d, 0x44, 0x13, 0x1b, 0xef, 0xa6, 0x22, 0x0f, 0xc0, 0x0b, 0xf0, 0x3a, 0xbc,
	0x1c, 0xda, 0x59, 0x3b, 0xb1, 0x9d, 0x50, 0x72, 0xb7, 0x7b, 0xe6, 0xcc, 0x8c, 0xf7, 0xcc, 0x19,
	0x43, 0xe3, 0x2a, 0x8e, 0x06, 0x4f, 0xe3, 0x70, 0xa6, 0xa8, 0x1b, 0xc5, 0xa1, 0x0a, 0xd1, 0xd6,
	0x88, 0x78, 0x0c, 0xb6, 0x1f, 0x86, 0x13, 0xac, 0x41, 0x79, 0x3c, 0xf4, 0xac, 0xb6, 0xd5, 0xd9,
	0xf1, 0xcb, 0xe3, 0x21, 0x22, 0xd8, 0xd3, 0x60, 0x42, 0x5e, 0x99, 0x11, 0x3e, 0x8b, 0x27, 0xe0,
	0x7c, 0xbe, 0x0e, 0xe6, 0x14, 0x67, 0xd8, 0xf6, 0x5f, 0xd9, 0x9f, 0xc0, 0x7e, 0x3d, 0x0a, 0x14,
	0x1e, 0x81, 0x1b, 0x71, 0x56, 0x9f, 0x29, 0xa6, 0x05, 0x18, 0xe8, 0x63, 0x30, 0x21, 0x9d, 0xac,
	0xe8, 0x87, 0x4a, 0x93, 0xf5, 0x99, 0xb1, 0xf1, 0x84, 0xbc, 0x4a, 0xdb, 0xea, 0x54, 0x7c, 0x3e,
	0x8b, 0x07, 0x50, 0x7f, 0x4b, 0xea, 0x32, 0xfc, 0x46, 0x53, 0x9f, 0xbe, 0xcf, 0x48, 0xaa, 0x45,
	0x5f, 0x2b, 0xd3, 0xf7, 0x1c, 0x6a, 0x4b, 0x9a, 0x9c, 0x5d, 0x2b, 0xdc, 0x87, 0x2d, 0xa5, 0xaf,
	0x09, 0xcd, 0x5c, 0xf0, 0x1e, 0xec, 0x06, 0x83, 0x01, 0x49, 0xd9, 0x37, 0x41, 0xd3, 0xde, 0x35,
	0x18, 0xa7, 0x8b, 0x26, 0xec, 0xf9, 0xf4, 0x35, 0x26, 0x39, 0xca, 0x76, 0x15, 0xa7, 0x80, 0x79,
	0x98, 0xbb, 0x6c, 0x50, 0xef, 0x05, 0xd4, 0xdf, 0x85, 0xe3, 0xa9, 0x16, 0x3c, 0x7d, 0xc1, 0x21,
	0x6c, 0xc7, 0x61, 0x38, 0xe9, 0x2f, 0xc4, 0x77, 0xf4, 0xf5, 0x7c, 0xbd, 0xa4, 0xbf, 0x2c, 0xa8,
	0x2d, 0x0b, 0x70, 0xd7, 0x03, 0x70, 0x62, 0x3e, 0x71, 0x7a, 0xd5, 0x4f, 0x6e, 0x78, 0x17, 0x6c,
	0x5d, 0x88, 0xd3, 0xdd, 0x1e, 0x74, 0xf5, 0xb0, 0xbb, 0x9c, 0xc7, 0x38, 0x3e, 0x84, 0x6d, 0x33,
	0x02, 0xe9, 0x55, 0xda, 0x95, 0x8e, 0xdb, 0xdb, 0x35, 0x14, 0x33, 0x60, 0x3f, 0x0d, 0x62, 0x1b,
	0xb6, 0x06, 0xa3, 0x40, 0x49, 0xcf, 0x66, 0x56, 0x52, 0x48, 0x0f, 0xd6, 0x37, 0x01, 0x71, 0x0c,
	0x8d, 0xf7, 0x14, 0xdc, 0xd0, 0x26, 0xaf, 0x12, 0x8f, 0xa0, 0x9e, 0x21, 0xdf, 0xf6, 0x02, 0xf1,
	0x12, 0xf0, 0x03, 0x49, 0x19, 0x5c, 0xd1, 0xa6, 0x7a, 0x15, 0x5d, 0x24, 0x8e, 0xe1, 0xff, 0x5c,
	0x89, 0x5b, 0xfb, 0x75, 0xe0, 0xbf, 0x0b, 0x15, 0x53, 0xf0, 0xef, 0x47, 0xfc, 0xb6, 0xa0, 0x96,
	0x52, 0x65, 0x14, 0x4e, 0x25, 0xe1, 0x09, 0xd8, 0x6a, 0x1e, 0x19, 0x23, 0xd6, 0x7a, 0x47, 0x46,
	0xa5, 0x3c, 0x27, 0xb9, 0x5e, 0xce, 0x23, 0xf2, 0x99, 0xac, 0x67, 0xa4, 0x25, 0xcc, 0xcf, 0x88,
	0xa5, 0x65, 0x1c, 0xef, 0x83, 0x63, 0xc6, 0xc0, 0x6b, 0x50, 0x1c, 0x51, 0x12, 0x13, 0x5d, 0x80,
	0x65, 0x65, 0xac, 0x9a, 0xad, 0x6b, 0x94, 0x10, 0xc0, 0xd1, 0x5e, 0xa1, 0x61, 0xc3, 0xd2, 0x67,
	0x96, 0x7d, 0xd8, 0x28, 0xf7, 0x7e, 0x56, 0xc0, 0xd5, 0x94, 0x0b, 0x8a, 0x6f, 0xc6, 0x03, 0xc2,
	0x33, 0xa8, 0xa6, 0xfb, 0x82, 0x4d, 0xd3, 0xa1, 0xb0, 0x66, 0xad, 0xfd, 0x22, 0xcc, 0x82, 0x95,
	0xf0, 0x0d, 0xec, 0x66, 0x17, 0x01, 0xef, 0x24, 0x36, 0x5b, 0xdd, 0x99, 0x96, 0xb7, 0x2e, 0x94,
	0x94, 0x39, 0x83, 0x6a, 0xea, 0xea, 0xf4, 0x0b, 0x0a, 0x6b, 0x92, 0x7e, 0x41, 0xde, 0xfc, 0xa2,
	0x84, 0xcf, 0x61, 0x67, 0xe1, 0x27, 0x3c, 0x30, 0xa4, 0xa2, 0x1b, 0x5b, 0xcd, 0x15, 0x3c, 0xc9,
	0x7e, 0x05, 0x6e, 0xc6, 0x1f, 0x98, 0x7c, 0xe3, 0xaa, 0xeb, 0x5a, 0x87, 0x6b, 0x22, 0x49, 0x8d,
	0x53, 0x70, 0x8c, 0xfc, 0xb8, 0x97, 0x9f, 0x7a, 0xee, 0xc3, 0xf3, 0x56, 0x10, 0xa5, 0x67, 0xd6,
	0x17, 0x87, 0x7f, 0xc3, 0x27, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xcf, 0xaa, 0x77, 0x9a,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResult, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResult, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResult, error)
	LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResult, error)
	MessageRoom(ctx context.Context, in *MessageRoomRequest, opts ...grpc.CallOption) (*MessageRoomResult, error)
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ChatService_StreamClient, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResult, error) {
	out := new(GetTokenResult)
	err := c.cc.Invoke(ctx, "/grpc.ChatService/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResult, error) {
	out := new(RefreshTokenResult)
	err := c.cc.Invoke(ctx, "/grpc.ChatService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResult, error) {
	out := new(JoinRoomResult)
	err := c.cc.Invoke(ctx, "/grpc.ChatService/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResult, error) {
	out := new(LeaveRoomResult)
	err := c.cc.Invoke(ctx, "/grpc.ChatService/LeaveRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MessageRoom(ctx context.Context, in *MessageRoomRequest, opts ...grpc.CallOption) (*MessageRoomResult, error) {
	out := new(MessageRoomResult)
	err := c.cc.Invoke(ctx, "/grpc.ChatService/MessageRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ChatService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/grpc.ChatService/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_StreamClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type chatServiceStreamClient struct {
	grpc.ClientStream
}

func (x *chatServiceStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResult, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResult, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResult, error)
	LeaveRoom(context.Context, *LeaveRoomRequest) (*LeaveRoomResult, error)
	MessageRoom(context.Context, *MessageRoomRequest) (*MessageRoomResult, error)
	Stream(*StreamRequest, ChatService_StreamServer) error
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ChatService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ChatService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ChatService/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ChatService/LeaveRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).LeaveRoom(ctx, req.(*LeaveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MessageRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MessageRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ChatService/MessageRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MessageRoom(ctx, req.(*MessageRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).Stream(m, &chatServiceStreamServer{stream})
}

type ChatService_StreamServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type chatServiceStreamServer struct {
	grpc.ServerStream
}

func (x *chatServiceStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _ChatService_GetToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _ChatService_RefreshToken_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _ChatService_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _ChatService_LeaveRoom_Handler,
		},
		{
			MethodName: "MessageRoom",
			Handler:    _ChatService_MessageRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ChatService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/route.proto",
}
